### PR TITLE
Docker v1.10

### PR DESCRIPTION
**Pull request by ailispaw**

### CODE REVIEW

**Comment by cedvan** [comment]
:+1:

**Comment by ailispaw** [comment]
Thanks for :+1: .
I'm not a big fun of v1.10.
Do you have any specific reason to use v1.10?

**Comment by cedvan** [comment]
Yes, rancher network need docker >= 1.10 :)

**Comment by ailispaw** [comment]
OK, I will consider it.

FYI:
You can try v1.10 in the current release by installing any `docker` binary like `pkg`.
Then replace `/usr/bin/docker` with `/opt/bin/docker` in `/etc/init.d/docker` script and
`/etc/init.d/docker restart`.

**Comment by cedvan** [comment]
`$ pkg install docker` ? How target a specific version ?

**Comment by ailispaw** [comment]
Nope.

``` bash
$ wget https://get.docker.com/builds/Linux/x86_64/docker-1.10.2
$ chmod +x docker-1.10.2
$ sudo mv docker-1.10.2 /opt/bin/docker
```

**Comment by cedvan** [comment]
Oh great ! Thank you :)

**Comment by ailispaw** [comment]
It seems Docker v1.10.3 is coming.

**Comment by cedvan** [comment]
Nice !

**Comment by ailispaw** [comment]
Now you can switch Docker to v1.10.3 as below.

``` bash
[docker@docker-root ~]$ sudo /etc/init.d/docker restart v1.10.3
```

**Comment by ailispaw** [comment]
Closing because of #29

**Pull request closed without merging**
